### ISSUE TITLE
Show excerpts on the homepage

### ISSUE THREAD

**Issue by katydecorah** [double-great/listen#15]
@jsnmrs what do you think about adding excerpts to the homepage? I'm on the fence. I think they add nice context, but want to make sure it's not too overwhelming:

Current | Proposed
---|---
![image](https://user-images.githubusercontent.com/2180540/86538047-7dfe3a00-bec1-11ea-8c0b-8fe7ae3899f5.png) | ![image](https://user-images.githubusercontent.com/2180540/86538032-645cf280-bec1-11ea-83e9-f9e181e56701.png)

**Comment by jsnmrs** [comment]
@katydecorah I like the excerpts a lot! 

While looking at the homepage template: what do you think of hiding the date on the homepage? It would still show on the post pages (and could incorporate updated date, too).

**Comment by katydecorah** [comment]
> what do you think of hiding the date on the homepage? It would still show on the post pages (and could incorporate updated date, too)

Sounds good! I'll get a PR started
