### ISSUE TITLE
Do other punctuation create audible pause?

### ISSUE THREAD

**Issue by katydecorah** [double-great/listen#19]
For example: commas, dashes, ellipsis

**Comment by jsnmrs** [comment]
@katydecorah add findings to the same post (<https://doublegreat.dev/listen/punctuation-in-alt-text/>)?

How does this set look?
- `A shape, with eight sides`
- `A shape - with eight sides` (hyphen)
- `A shape – with eight sides` (en dash)
- `A shape — with eight sides` (em dash)
- `A shape... with eight sides` (three periods)
- `A shape… with eight sides` (ellipsis)

**Comment by katydecorah** [comment]
> add findings to the same post

Yes!

> How does this set look?

Perfect

**Comment by jsnmrs** [comment]
Add to punctuation: 
- Semicolon
- colon
- quotes


Characters post: 
- ampersand
- dollar sign

**Comment by katydecorah** [comment]
Re: quotes, smart quotes and dumb quotes

**Comment by jsnmrs** [comment]
Closing this one — captured other characters for consideration in #23
