### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by katydecorah** [double-great/listen#20]

**Comment by katydecorah** [comment]
Ideas:
👂
🔈
🎧

**Comment by jsnmrs** [comment]
I like 🎧. Ok with you?

Assigning to myself to create and use this SVG + ICO fallback approach:
https://github.com/jsnmrs/jasonmorris/blob/main/_includes/header.html#L12-L13

**Comment by katydecorah** [comment]
Sounds good!
